#!/bin/bash

if [ -f /etc/sysconfig/cyanite ]; then
    . /etc/sysconfig/cyanite
fi

JAR="$EXTRA_CLASSPATH:/usr/lib/cyanite/cyanite.jar"
CONFIG="/etc/cyanite.yaml"

exec java $EXTRA_JAVA_OPTS $OPTS -cp "$JAR" io.cyanite "$CONFIG"
